import Head from "next/head";
import styles from "@/styles/Home.module.css";
import DisplayImage from "@/Components/DisplayImage";
import ColorThief from "colorthief";
import { useState } from "react";

const gallery =<i className="fas fa-images"></i>

export default function Home() {

  const[uploadedImage,setUploadedImage] = useState(null);
  const[colorPalette,setColorPalette] = useState(null);

  const uploadImage = (e) =>{
    const file= e.target.files[0]
    const reader = new FileReader()

    reader.onload = async (event) => {
      const img = new Image()

      img.onload = () => {
        const colorThief = new ColorThief();
        const colorPalette = colorThief.getPalette(img,10);
        setUploadedImage(event.target.result)
        setColorPalette(colorPalette)
      };
      img.src = event.target.result;
    };

    reader.readAsDataURL(file);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" 
        integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" 
        crossorigin="anonymous" 
        referrerpolicy="no-referrer" />
      </Head>
      <header>
        <h1>Image Color Palette EyeDropper</h1>
        <div className="input">
          <label htmlFor="file">{gallery}Upload Image</label>
          <input type="file" id="file" hidden onChange={uploadImage}/>
        </div>
      </header>
      <main className={styles.main}>
        <DisplayImage uploadedImage={uploadedImage} colorPalette={colorPalette}/>
      </main>
    </>
  );
}